### ISSUE TITLE
Add a way to set custom css classes

### ISSUE THREAD

**Issue by equinusocio** [interactivethings/catalog#361]
Hi, since we ca set a custom css it could be useful having a way to set custom css classes to each speciment and use our CSS. 

Something like 

```
```html|class-MyClass
```

And

```
```html
class: "MyClass"
```

**Comment by herrstucki** [comment]
Can you describe the exact need for this? To which element would this class be applied?

**Comment by equinusocio** [comment]
Whit a custom css class wi can target elements easily because now 80% are inline style or classnames generated with CSS modules or something similar. The custom class should be applied to the speciment outer container.

**Comment by herrstucki** [comment]
Okay, that makes sense.

We'll change the styling approach anyway in the next few months (replace Radium with something else) …

So I wonder if making customizations like this is something we should support better. For example by exposing a way to override styles through the theme configuration itself or by adding readable and stable class names to all elements, so they can be targeted directly with CSS.

**Comment by equinusocio** [comment]
What about using css custom properties? You can expose specimens css properties that uses the css power.

```css
.SpecimentRoot {
  --specimentName-background: var(--catalog-specimentname-background, #FFF);
}

.SpecimentInnerElement {
  background-color: var(--specimentName);
}

```
