### ISSUE TITLE
HR divider: how to add, either in Markdown or as specimen?

### ISSUE THREAD

**Issue by dlewand691** [interactivethings/catalog#389]
I'd like to add an `<hr>` divider but not clear on the proper way. Have tried using and none seem to work:

```
***
---
___
```

**Comment by dardub** [comment]
I found that it renders an hr but the default styles hide it.

```css
.catalog-18yq8b2-hr-Styled {
    border: none;
    -webkit-flex-basis: 100%;
    -ms-flex-preferred-size: 100%;
    flex-basis: 100%;
    margin: 0;
    height: 0;
}
```
