### ISSUE TITLE
Support YAML Specimen Config?

### ISSUE THREAD

**Issue by herrstucki** [interactivethings/catalog#61]
Instead of or in addition to verbose and error-prone JSON (when written manually), we could support the more readable YAML for Specimen configuration.

Example:

```json
{
    "title": "Catalog Logo (.svg)",
    "filename": "catalog-logo",
    "subtitle": "8 KB",
    "url": "docs/assets/catalog_logo.svg"
}
```

```yaml
title: Catalog Logo (.svg)
filename: catalog-logo
subtitle: 8 KB
url: docs/assets/catalog_logo.svg
```

Since Markdown Front Matter is usually written in YAML, this would also make a natural fit.
